version: 2.1
orbs:
  architect: giantswarm/architect@4.27.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          name: app-catalog
          context: "architect"
          # executor: "app-build-suite" # uncomment this if you want automatic metadata generation and helm chart linting
          app_catalog: "default-catalog"
          app_catalog_test: "default-test-catalog"
          chart: "observability-bundle"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: aws-app-collection
          context: "architect"
          app_name: "observability-bundle"
          app_namespace: "giantswarm"
          app_collection_repo: "aws-app-collection"
          requires:
            - app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          name: azure-app-collection
          context: "architect"
          app_name: "observability-bundle"
          app_namespace: "giantswarm"
          app_collection_repo: "azure-app-collection"
          requires:
            - app-catalog
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
