version: 2.1
orbs:
  architect: giantswarm/architect@6.6.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
    - architect/push-to-app-catalog:
        name: app-catalog
        context: architect
        executor: app-build-suite
        app_catalog: default-catalog
        app_catalog_test: default-test-catalog
        chart: observability-bundle
          # Trigger job on git tag.
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore:
            - main
            - master
