clusterID: ""
organization: ""

userConfig:
  kubePrometheusStack:
    configMap:
      values:
        global:
          rbac:
            pspEnabled: false
        kube-prometheus-stack:
          defaultRules:
            create: false
          alertmanager:
            enabled: false
          grafana:
            enabled: false
            rbac:
              pspEnabled: false
          kube-state-metrics:
            podSecurityPolicy:
              enabled: false
            networkPolicy:
              flavor: cilium
          prometheus-node-exporter:
            rbac:
              pspEnabled: false
          prometheus:
            enabled: false
          prometheusOperator:
            networkPolicy:
              flavor: cilium
              matchLabels:
                app.kubernetes.io/instance: kube-prometheus-stack
                app.kubernetes.io/part-of: kube-prometheus-stack
                application.giantswarm.io/team: atlas
  prometheusAgent:
    configMap:
      values:
        prometheus-agent:
          psp:
            enabled: false
  promtail:
    configMap:
      values:
        ciliumNetworkPolicy:
          enabled: true
        promtail:
          rbac:
            pspEnabled: false
          networkPolicy:
            enabled: false

apps:
  prometheusOperatorCrd:
    appName: prometheus-operator-crd
    chartName: prometheus-operator-crd
    catalog: default
    enabled: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/prometheus-operator-crd
    version: 9.0.0

  kubePrometheusStack:
    appName: kube-prometheus-stack
    chartName: kube-prometheus-stack
    catalog: default
    dependsOn: prometheus-operator-crd
    enabled: true
    namespace: kube-system
    skipCRDs: true
    timeout: 15m
    # used by renovate
    # repo: giantswarm/kube-prometheus-stack
    version: 8.1.2

  prometheusAgent:
    appName: prometheus-agent
    chartName: prometheus-agent
    catalog: default
    dependsOn: prometheus-operator-crd
    enabled: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/prometheus-agent-app
    version: 0.6.7
    # a list of extraConfigs for the App,
    # It can be secret or configmap
    # https://github.com/giantswarm/rfc/tree/main/multi-layer-app-config#example
    extraConfigs:
      - kind: secret
        name: "{{ $.Values.clusterID }}-remote-write-secret"
        namespace: "{{ $.Release.Namespace }}"
      - kind: configMap
        name: "{{ $.Values.clusterID }}-remote-write-config"
        namespace: "{{ $.Release.Namespace }}"

  promtail:
    appName: promtail
    chartName: promtail
    catalog: giantswarm
    enabled: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/promtail-app
    version: 1.5.0
    # a list of extraConfigs for the App,
    # It can be secret or configmap
    # https://github.com/giantswarm/rfc/tree/main/multi-layer-app-config#example
    extraConfigs:
      - kind: secret
        name: "{{ $.Values.clusterID }}-logging-secret"
        namespace: "{{ $.Release.Namespace }}"
      - kind: configMap
        name: "{{ $.Values.clusterID }}-logging-config"
        namespace: "{{ $.Release.Namespace }}"

  grafanaAgent:
    appName: grafana-agent
    chartName: grafana-agent
    catalog: giantswarm
    enabled: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/grafana-agent-app
    version: 0.4.0
    # a list of extraConfigs for the App,
    # It can be secret or configmap
    # https://github.com/giantswarm/rfc/tree/main/multi-layer-app-config#example
    extraConfigs:
      - kind: configMap
        name: "{{ $.Values.clusterID }}-grafana-agent-config"
        namespace: "{{ $.Release.Namespace }}"
      - kind: secret
        name: "{{ $.Values.clusterID }}-grafana-agent-secret"
        namespace: "{{ $.Release.Namespace }}"
