clusterID: ""
managementCluster: ""
organization: ""

userConfig:
  kubePrometheusStack:
    configMap:
      values:
        kube-prometheus-stack:
          defaultRules:
            create: false
          alertmanager:
            enabled: false
          grafana:
            enabled: false
          kube-state-metrics:
            networkPolicy:
              flavor: cilium
            prometheus:
              monitor:
                metricRelabelings:
                  # GS addition to reduce cardinality
                  # drop unused kube-state-metrics metrics with the highest cardinality as they increase Prometheus memory usage
                  - sourceLabels: [__name__]
                    regex: kube_(.+_annotations|secret_type|pod_status_qos_class|pod_tolerations|pod_status_scheduled|replicaset_metadata_generation|replicaset_status_observed_generation|replicaset_annotations|replicaset_status_fully_labeled_replicas|.+_metadata_resource_version)
                    action: drop
                  # drop image_id label
                  - action: labeldrop
                    regex: image_id
                  # GS addition for dashboards
                  - sourceLabels: [label_topology_kubernetes_io_region]
                    targetLabel: region
                    replacement: ${1}
                    action: replace
                  - sourceLabels: [label_topology_kubernetes_io_zone]
                    targetLabel: zone
                    replacement: ${1}
                    action: replace
                  - action: labeldrop
                    regex: label_topology_kubernetes_io_region|label_topology_kubernetes_io_zone
                  # Override with label for AWS clusters if exists.
                  - sourceLabels: [label_giantswarm_io_machine_deployment]
                    targetLabel: nodepool
                    replacement: ${1}
                    action: replace
                  # Override with label for Azure clusters if exists.
                  - sourceLabels: [label_giantswarm_io_machine_pool]
                    targetLabel: nodepool
                    replacement: ${1}
                    action: replace
                  # CAPI monitoring specific BEGIN
                  # (see kube-state-metrics rules in https://github.com/giantswarm/observability-bundle/tree/main/helm/observability-bundle/ksm-configurations)
                  - action: replace
                    sourceLabels:
                      - __name__
                      - cluster_name
                    regex: "^capi_.+;(.+)"
                    replacement: "${1}"
                    targetLabel: cluster_id
                  # Use the `name` label as cluster name if the above fails
                  - action: replace
                    sourceLabels:
                      - __name__
                      - cluster_name
                      - name
                    regex: "^capi_.+;;(.+)"
                    replacement: "${1}"
                    targetLabel: cluster_id
                  # CAPI monitoring specific END
                  # Set cluster_type for CAPI cluster metrics based on whether the cluster is the management cluster
                  - sourceLabels: [__name__]
                    regex: "capi_cluster_.+"
                    targetLabel: cluster_type
                    replacement: workload_cluster
                  - sourceLabels: [__name__, cluster_id]
                    regex: "capi_cluster_.+;{{ $.Values.managementCluster }}"
                    targetLabel: cluster_type
                    replacement: management_cluster
          prometheus:
            enabled: false
          prometheusOperator:
            admissionWebhooks:
              objectSelector:
                matchExpressions:
                  - key: application.giantswarm.io/prometheus-rule-kind
                    operator: NotIn
                    values:
                      - loki
                  - key: observability.giantswarm.io/rule-type
                    operator: NotIn
                    values:
                      - logs
            networkPolicy:
              flavor: cilium
              matchLabels:
                app.kubernetes.io/instance: kube-prometheus-stack
                app.kubernetes.io/part-of: kube-prometheus-stack
                application.giantswarm.io/team: atlas

apps:
  alloyEvents:
    appName: alloy-events
    chartName: alloy
    catalog: default
    dependsOn: prometheus-operator-crd
    enabled: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/alloy-app
    version: 0.16.1
    # a list of extraConfigs for the App,
    # It can be secret or configmap
    # https://github.com/giantswarm/rfc/tree/main/multi-layer-app-config#example
    extraConfigs:
      - kind: secret
        name: "{{ $.Values.clusterID }}-events-logger-secret"
        namespace: "{{ $.Release.Namespace }}"
      - kind: configMap
        name: "{{ $.Values.clusterID }}-events-logger-config"
        namespace: "{{ $.Release.Namespace }}"

  alloyLogs:
    appName: alloy-logs
    chartName: alloy
    catalog: default
    dependsOn: prometheus-operator-crd
    enabled: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/alloy-app
    version: 0.16.1
    # a list of extraConfigs for the App,
    # It can be secret or configmap
    # https://github.com/giantswarm/rfc/tree/main/multi-layer-app-config#example
    extraConfigs:
      - kind: secret
        name: "{{ $.Values.clusterID }}-logging-secret"
        namespace: "{{ $.Release.Namespace }}"
      - kind: configMap
        name: "{{ $.Values.clusterID }}-logging-config"
        namespace: "{{ $.Release.Namespace }}"

  alloyMetrics:
    appName: alloy-metrics
    chartName: alloy
    catalog: default
    dependsOn: prometheus-operator-crd
    enabled: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/alloy-app
    version: 0.16.1
    # a list of extraConfigs for the App,
    # It can be secret or configmap
    # https://github.com/giantswarm/rfc/tree/main/multi-layer-app-config#example
    extraConfigs:
      - kind: secret
        name: "{{ $.Values.clusterID }}-monitoring-secret"
        namespace: "{{ $.Release.Namespace }}"
      - kind: configMap
        name: "{{ $.Values.clusterID }}-monitoring-config"
        namespace: "{{ $.Release.Namespace }}"

  prometheusOperatorCrd:
    appName: prometheus-operator-crd
    chartName: prometheus-operator-crd
    catalog: default
    enabled: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/prometheus-operator-crd
    version: 19.0.1

  kubePrometheusStack:
    appName: kube-prometheus-stack
    chartName: kube-prometheus-stack
    catalog: default
    dependsOn: prometheus-operator-crd
    enabled: true
    namespace: kube-system
    skipCRDs: true
    timeout: 15m
    # used by renovate
    # repo: giantswarm/kube-prometheus-stack-app
    version: 19.0.2
    extraConfigs: []
