clusterID: ""
organization: ""

apps:
  prometheus-operator-crd:
    appName: prometheus-operator-crd
    chartName: prometheus-operator-crd
    catalog: default
    enabled: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/prometheus-operator-crd
    version: 5.0.0
    # User values can be provided via a ConfigMap or Secret for each individual app
    userConfig: {}
    # a list of extraConfigs for the App,
    # It can be secret or configmap
    # https://github.com/giantswarm/rfc/tree/main/multi-layer-app-config#example
    extraConfigs: []

  prometheus-operator-app:
    appName: prometheus-operator-app
    chartName: prometheus-operator-app
    catalog: default
    dependsOn: prometheus-operator-crd
    enabled: true
    namespace: kube-system
    skipCRDs: true
    # used by renovate
    # repo: giantswarm/prometheus-operator-app
    version: 4.4.0
    userConfig:
      configMap:
        values: |
          prometheus-operator-app:
            defaultRules:
              create: false
            kubeProxy:
              enabled: false
            alertmanager:
              enabled: false
            grafana:
              enabled: false
            prometheus:
              enabled: false
    # a list of extraConfigs for the App,
    # It can be secret or configmap
    # https://github.com/giantswarm/rfc/tree/main/multi-layer-app-config#example
    extraConfigs: []

  prometheus-agent:
    appName: prometheus-agent
    chartName: prometheus-agent
    catalog: default
    dependsOn: prometheus-operator-crd
    enabled: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/prometheus-agent-app
    version: 0.5.3
    # User values can be provided via a ConfigMap or Secret for each individual app
    # using the structure shown below.
    userConfig:
      configMap:
        values: |
          prometheus-agent:
            serviceMonitorNamespaceSelector: {}
            serviceMonitorSelector:
              matchExpressions:
                - key: "application.giantswarm.io/team"
                  operator: "Exists"
            podMonitorNamespaceSelector: {}
            podMonitorSelector:
              matchExpressions:
                - key: "application.giantswarm.io/team"
                  operator: "Exists"
            serviceMonitor:
              enabled: true
              relabelings:
              # Add app label.
              - sourceLabels:
                - __meta_kubernetes_pod_label_app_kubernetes_io_name
                targetLabel: app
              # Add instance label.
              - sourceLabels:
                - __meta_kubernetes_pod_label_app_kubernetes_io_instance
                targetLabel: instance
              # Add node label.
              - sourceLabels:
                - __meta_kubernetes_pod_node_name
                targetLabel: node
              # Add team label.
              - sourceLabels:
                - __meta_kubernetes_pod_label_application_giantswarm_io_team
                targetLabel: team
    # a list of extraConfigs for the App,
    # It can be secret or configmap
    # https://github.com/giantswarm/rfc/tree/main/multi-layer-app-config#example
    extraConfigs:
      - kind: secret
        name: "{{ $.Values.clusterID }}-remote-write-secret"
        namespace: "{{ $.Release.Namespace }}"
      - kind: configMap
        name: "{{ $.Values.clusterID }}-remote-write-config"
        namespace: "{{ $.Release.Namespace }}"

  promtail-app:
    appName: promtail-app
    chartName: promtail
    catalog: giantswarm
    enabled: false
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/promtail-app
    version: 1.1.0
    # User values can be provided via a ConfigMap or Secret for each individual app
    userConfig: {}
    # a list of extraConfigs for the App,
    # It can be secret or configmap
    # https://github.com/giantswarm/rfc/tree/main/multi-layer-app-config#example
    extraConfigs:
      - kind: secret
        name: "{{ $.Values.clusterID }}-logging-secret"
        namespace: "{{ $.Release.Namespace }}"
      - kind: configMap
        name: "{{ $.Values.clusterID }}-logging-config"
        namespace: "{{ $.Release.Namespace }}"
