clusterID: ""
organization: ""

userConfig:
  kubePrometheusStack:
    configMap:
      values:
        kube-prometheus-stack:
          defaultRules:
            create: false
          alertmanager:
            enabled: false
          grafana:
            enabled: false
          kube-state-metrics:
            networkPolicy:
              flavor: cilium
          prometheus:
            enabled: false
          prometheusOperator:
            admissionWebhooks:
              objectSelector:
                matchExpressions:
                  - key: application.giantswarm.io/prometheus-rule-kind
                    operator: NotIn
                    values:
                      - loki
                  - key: observability.giantswarm.io/rule-type
                    operator: NotIn
                    values:
                      - logs
            networkPolicy:
              flavor: cilium
              matchLabels:
                app.kubernetes.io/instance: kube-prometheus-stack
                app.kubernetes.io/part-of: kube-prometheus-stack
                application.giantswarm.io/team: atlas

apps:
  alloyEvents:
    appName: alloy-events
    chartName: alloy
    catalog: default
    dependsOn: prometheus-operator-crd
    enabled: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/alloy-app
    version: 0.12.1
    # a list of extraConfigs for the App,
    # It can be secret or configmap
    # https://github.com/giantswarm/rfc/tree/main/multi-layer-app-config#example
    extraConfigs:
      - kind: secret
        name: "{{ $.Values.clusterID }}-events-logger-secret"
        namespace: "{{ $.Release.Namespace }}"
      - kind: configMap
        name: "{{ $.Values.clusterID }}-events-logger-config"
        namespace: "{{ $.Release.Namespace }}"

  alloyLogs:
    appName: alloy-logs
    chartName: alloy
    catalog: default
    dependsOn: prometheus-operator-crd
    enabled: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/alloy-app
    version: 0.12.1
    # a list of extraConfigs for the App,
    # It can be secret or configmap
    # https://github.com/giantswarm/rfc/tree/main/multi-layer-app-config#example
    extraConfigs:
      - kind: secret
        name: "{{ $.Values.clusterID }}-logging-secret"
        namespace: "{{ $.Release.Namespace }}"
      - kind: configMap
        name: "{{ $.Values.clusterID }}-logging-config"
        namespace: "{{ $.Release.Namespace }}"

  alloyMetrics:
    appName: alloy-metrics
    chartName: alloy
    catalog: default
    dependsOn: prometheus-operator-crd
    enabled: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/alloy-app
    version: 0.12.1
    # a list of extraConfigs for the App,
    # It can be secret or configmap
    # https://github.com/giantswarm/rfc/tree/main/multi-layer-app-config#example
    extraConfigs:
      - kind: secret
        name: "{{ $.Values.clusterID }}-monitoring-secret"
        namespace: "{{ $.Release.Namespace }}"
      - kind: configMap
        name: "{{ $.Values.clusterID }}-monitoring-config"
        namespace: "{{ $.Release.Namespace }}"

  prometheusOperatorCrd:
    appName: prometheus-operator-crd
    chartName: prometheus-operator-crd
    catalog: default
    enabled: true
    namespace: kube-system
    # used by renovate
    # repo: giantswarm/prometheus-operator-crd
    version: 17.0.0

  kubePrometheusStack:
    appName: kube-prometheus-stack
    chartName: kube-prometheus-stack
    catalog: default
    dependsOn: prometheus-operator-crd
    enabled: true
    namespace: kube-system
    skipCRDs: true
    timeout: 15m
    # used by renovate
    # repo: giantswarm/kube-prometheus-stack-app
    version: 18.0.0
    extraConfigs: []
