clusterName: ""
organization: ""

# User values can be provided via a ConfigMap or Secret for each individual app
# using the structure shown below.

# userConfig:
#   prometheus-operator-app:
#     configMap:
#       values: |
#         prometheusOperator:
#           enabled: true

userConfig:
  prometheus-operator-app:
    configMap:
      values: |
        defaultRules:
          create: false
        global:
          rbac:
            create: true
            pspEnabled: false
        alertmanager:
          enabled: false
        grafana:
          enabled: false
        kubeApiServer:
          enabled: true
        kubelet:
          enabled: false
        kubeControllerManager:
          enabled: true
        coreDns:
          enabled: false
        kubeEtcd:
          enabled: false
        kubeScheduler:
          enabled: true
        kubeProxy:
          enabled: false
        kubeStateMetrics:
          enabled: false
        nodeExporter:
          enabled: false
        prometheusOperator:
          enabled: true
          image:
            tag: v0.58.0
        prometheus:
          enabled: false

apps:
  operatorCrd:
    appName: prometheus-operator-crd
    chartName: prometheus-operator-crd
    catalog: giantswarm
    enabled: true
    namespace: monitoring
    version: 1.0.1

  operator:
    appName: prometheus-operator
    chartName: prometheus-operator-app
    catalog: giantswarm
    enabled: true
    namespace: monitoring
    version: 1.3.0

  agent:
    appName: prometheus-agent
    chartName: prometheus-agent-app
    catalog: giantswarm
    enabled: true
    namespace: monitoring
    version: 0.1.0
