name: observability-pack
serviceType: managed

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

image:
  registry: quay.io
  name: giantswarm/observability-pack
  tag: v0.0.1
  pullPolicy: IfNotPresent
