apiVersion: v1
data:
  values: |
    clusterID: w8eu8
    organization: mohamed
kind: ConfigMap
metadata:
  name: observability-pack-user-values
  namespace: w8eu8
---

apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    # Required version: 0.0.0
    app-operator.giantswarm.io/version: 0.0.0
    app.kubernetes.io/name: observability-pack
  name: observability-pack
  namespace: w8eu8
spec:
  catalog: giantswarm-playground-test
  kubeConfig:
    # Required
    inCluster: true
  name: observability-pack
  namespace: w8eu8
  userConfig:
    configMap:
      name: observability-pack-user-values
      namespace: w8eu8
  version: 0.0.0-42d43b02bce8f97442f3f3d42075110509186175
