apiVersion: v1
data:
  values: |
    clusterID: w8eu8
    organization: mohamed
kind: ConfigMap
metadata:
  name: observability-bundle-user-values
  namespace: w8eu8
---

apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    # Required version: 0.0.0
    app-operator.giantswarm.io/version: 0.0.0
    app.kubernetes.io/name: observability-bundle
  name: observability-bundle
  namespace: w8eu8
spec:
  catalog: default-test-catalog
  kubeConfig:
    # Required
    inCluster: true
  name: observability-bundle
  namespace: w8eu8
  userConfig:
    configMap:
      name: observability-bundle-user-values
      namespace: w8eu8
  version: 0.0.0-ae45ab37e0f78d79cb8c0db99ae6872a35a8b80b
