{{- range $key, $value := .Values.apps }}
{{- $appName := include "app.name" (dict "app" .appName "cluster" $.Values.clusterID "ns" $.Release.Namespace) }}
{{- if .enabled }}
---
apiVersion: application.giantswarm.io/v1alpha1
kind: App
metadata:
  labels:
    {{- include "labels.common" $ | nindent 4 }}
  name: {{ $appName }}
  namespace: {{ $.Release.Namespace }}
spec:
  catalog: {{ .catalog }}
  config:
    configMap:
      name: {{ $.Values.clusterID }}-cluster-values
      namespace: {{ $.Release.Namespace }}
  install:
    skipCRDs: {{.skipCRDs | default false }}
  kubeConfig:
    context:
      name: {{ $.Values.clusterID }}-admin@{{ $.Values.clusterID }}
    inCluster: false
    secret:
      name: {{ $.Values.clusterID }}-kubeconfig
      namespace: {{ $.Release.Namespace}}
  name: {{ .chartName }}
  namespace: {{ .namespace }}
  version: {{ .version }}
  {{- if or .extraConfigs (hasSuffix "prometheus-agent" $appName) }}
  extraConfigs:
  # If the app is the prometheus agent, we inject of the remote write secret create by the Prometheus Meta Operator
  {{- if hasSuffix "prometheus-agent" $appName }}
  - kind: secret
    {{- if hasPrefix "org-" $.Release.Namespace }}
    # App is deployed in the org- namespace so the secret name is prefixed by the cluster-id
    name: {{ printf "%s-remote-write-api-endpoint-config" $.Values.clusterID -}}
    {{- else }}
    # App is deployed in the cluster-id namespace so prefix is unneeded
    name: remote-write-api-endpoint-config
    {{- end }}
    namespace: {{ $.Release.Namespace }}
  {{- end }}
  {{- range $extraConfig := .extraConfigs }}
  - kind: {{ $extraConfig.kind }}
    name: {{ $extraConfig.name }}
    namespace: {{ $extraConfig.namespace }}
  {{- end }}
  {{- end }}
  {{- if .userConfig }}
  {{- if or .userConfig.configMap .userConfig.secret }}
  userConfig:
    {{- if .userConfig.configMap }}
    configMap:
      name: {{ $appName }}-user-values
      namespace: {{ $.Release.Namespace }}
    {{- end }}
    {{- if .userConfig.secret }}
    secret:
      name: {{ $appName }}-user-secrets
      namespace: {{ $.Release.Namespace }}
    {{- end }}
  {{- end }}
  {{- end }}
{{- end }}
{{- if .userConfig }}
{{- if .userConfig.configMap }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "labels.common" $ | nindent 4 }}
  name: {{ $appName }}-user-values
  namespace: {{ $.Release.Namespace }}
data:
  {{- (tpl (.userConfig.configMap | toYaml | toString) $) | nindent 2 }}
{{- end }}
{{- if .userConfig.secret }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "labels.common" $ | nindent 4 }}
  name: {{ $appName }}-user-secrets
  namespace: {{ $.Release.Namespace }}
stringData:
  {{- (tpl (.userConfig.secret | toYaml | toString) $) | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
