apiVersion: v1
data:
  values: |
    ciliumNetworkPolicy:
      enabled: {{ .Values.ciliumNetworkPolicy.enabled }}
    promtail:
      rbac:
        pspEnabled: {{ not .Values.global.podSecurityStandards.enforced }}
      networkPolicy:
        enabled: {{ not .Values.ciliumNetworkPolicy.enabled }}
kind: ConfigMap
metadata:
  name: "{{ $.Values.clusterID }}-promtail-app-extraconfig"
  namespace: "{{ $.Release.Namespace }}"
