apiVersion: v1
data:
  values: |
    {{- if .Values.global.podSecurityStandards.enforced }}
    global:
      rbac:
        pspEnabled: false
    {{- end }}
    prometheus-operator-app:
      defaultRules:
        create: false
      alertmanager:
        enabled: false
      grafana:
        enabled: false
        {{- if .Values.global.podSecurityStandards.enforced }}
        rbac:
          pspEnabled: false
        {{- end }}
      {{- if or .Values.global.podSecurityStandards.enforced .Values.ciliumNetworkPolicy.enabled }}
      kube-state-metrics:
        {{- if .Values.global.podSecurityStandards.enforced }}
        podSecurityPolicy:
          enabled: false
        {{- end }}
        {{- if .Values.ciliumNetworkPolicy.enabled }}
        networkPolicy:
          flavor: cilium
        {{- end }}
      {{- end }}
      {{- if .Values.global.podSecurityStandards.enforced }}
      prometheus-node-exporter:
        rbac:
          pspEnabled: false
      {{- end }}
      prometheus:
        enabled: false
      {{- if .Values.ciliumNetworkPolicy.enabled }}
      prometheusOperator:
        networkPolicy:
          flavor: cilium
          matchLabels:
            app.kubernetes.io/instance: prometheus-operator-app
            app.kubernetes.io/part-of: prometheus-operator-app
            application.giantswarm.io/team: atlas
      {{- end }}
kind: ConfigMap
metadata:
  name: "{{ $.Values.clusterID }}-prometheus-operator"
  namespace: "{{ $.Release.Namespace }}"
