apiVersion: v1
data:
  values: |
    prometheus-agent:
      psp:
        enabled: {{ not .Values.global.podSecurityStandards.enforced }}
kind: ConfigMap
metadata:
  name: "{{ $.Values.clusterID }}-prometheus-agent-extraconfig"
  namespace: "{{ $.Release.Namespace }}"
