apiVersion: v1
data:
  values: |
    prometheus-operator-app:
      defaultRules:
        create: false
      kubeProxy:
        enabled: false
      alertmanager:
        enabled: false
      grafana:
        enabled: false
      prometheus:
        enabled: false
      {{- if .Values.ciliumNetworkPolicy.enabled }}
      prometheusOperator:
        networkPolicy:
          flavor: cilium
          matchLabels:
            app.kubernetes.io/instance: prometheus-operator-app
            app.kubernetes.io/part-of: prometheus-operator-app
            application.giantswarm.io/team: atlas
      kube-state-metrics:
        networkPolicy:
          flavor: cilium
      {{- end }}
kind: ConfigMap
metadata:
  name: "{{ $.Values.clusterID }}-prometheus-operator"
  namespace: "{{ $.Release.Namespace }}"
