rbac:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs: ["list", "watch"]

resources:
  - groupVersionKind:
      group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      version: v1
    metricNamePrefix: capi_crd
    labelsFromPath:
      resource_name: [metadata, name]
    metrics:
      - name: "info"
        help: "CAPI CRD Info"
        each:
          type: Info
          info:
            path: [spec, versions]
            labelsFromPath:
              version: [name]
