rbac:
  - apiGroups:
      - postgresql.cnpg.io
    resources:
      - clusters
    verbs: ["list", "watch"]

resources:
  - groupVersionKind:
      group: postgresql.cnpg.io
      version: v1
      kind: Cluster

    labelsFromPath:
      namespace: [metadata, namespace]
      cluster: [metadata, name]

    metrics:
      - name: kube_cnpg_cluster_status_info
        help: "Static info about a CloudNativePG Cluster including its status phase."
        each:
          type: Gauge
          value: 1
        labelsFromPath:
          phase: [status, phase]

      - name: kube_cnpg_cluster_spec_instances
        help: "The desired number of instances for this CloudNativePG cluster (spec.instances)."
        each:
          type: Gauge
          valueFrom: '{{ if .spec.instances }}{{ .spec.instances }}{{ else }}0{{ end }}'

      - name: kube_cnpg_cluster_status_ready_instances
        help: "The number of ready instances of the CloudNativePG cluster (status.readyInstances)."
        each:
          type: Gauge
          valueFrom: '{{ if .status.readyInstances }}{{ .status.readyInstances }}{{ else }}0{{ end }}'
