rbac:
  - apiGroups:
      - source.toolkit.fluxcd.io
    resources:
      - helmrepositories
    verbs: ["list", "watch"]

resources:
  - groupVersionKind:
      group: source.toolkit.fluxcd.io
      kind: HelmRepository
      version: v1beta2
    metricNamePrefix: flux_helmrepository
    metrics:
      - name: "resource_info"
        help: "The current state of a Flux HelmRepository resource."
        each:
          type: Info
          info:
            labelsFromPath:
              name: [metadata, name]
        labelsFromPath:
          exported_namespace: [metadata, namespace]
          ready: [status, conditions, "[type=Ready]", status]
          suspended: [spec, suspend]
          revision: [status, artifact, revision]
          url: [spec, url]
