rbac:
  - apiGroups:
      - notification.toolkit.fluxcd.io
    resources:
      - providers
    verbs: ["list", "watch"]

resources:
  - groupVersionKind:
      group: notification.toolkit.fluxcd.io
      kind: Provider
      version: "*"
    metricNamePrefix: gotk
    metrics:
      - name: "resource_info"
        help: "The current state of a Flux Provider resource."
        each:
          type: Info
          info:
            labelsFromPath:
              name: [metadata, name]
        labelsFromPath:
          exported_namespace: [metadata, namespace]
          suspended: [spec, suspend]
